### ISSUE TITLE
ValueError while using the wrapper

### ISSUE THREAD

**Issue by izxxr** [madeyoga/ytpy#7]
```
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/container/sly/cogs/utility.py", line 235, in youtube
    response = await client.search(query, max_results=5)
  File "/home/container/.local/lib/python3.8/site-packages/ytpy/youtube.py", line 124, in search
    start_index = (page_content.index(start_feature) + len(start_feature) + 3)
ValueError: substring not found
```
is the error I get when using search. My code is:
```py
async def youtube(self, ctx, *, query=None):
        if query == None:
            await ctx.send(Emoji.info+" Please provide a search term.")
            return

        session = aiohttp.ClientSession()
        client = YoutubeClient(session)
        response = await client.search(query, max_results=5)
        await session.close()
        titles = []
        e = 0
        for i in response:
            e += 1
            titles.append(f'`{e}`. [{i["title"]}](https://www.youtube.com/watch?v='+i["id"]+')'+'\n')
        
        embed = discord.Embed(title=f"Fetched {len(titles)} results from YouTube.", 
            description=''.join(titles), color=Color.error
            )
        await ctx.send(embed=embed)
```

**Comment by madeyoga** [comment]
Hello! Would you mind providing more information on how the error occurred
- ytpy version
- `query` string you passed into the `client.search()`

**Comment by izxxr** [comment]
> Hello! Would you mind providing more information on how the error occurred
> 
> * ytpy version
> * `query` string you passed into the `client.search()`

YTPY version is according to pip is: 2021.1.31, And the query was: 'Never gonna give you up' :smile:

**Comment by izxxr** [comment]
Is this ever gonna be fixed?

**Comment by madeyoga** [comment]
Hi! Sorry for the slow fix, I still have no idea what causes this error in your machine, 

I have tried running this script on my machine. 
```python
from ytpy import YoutubeClient
import asyncio
import aiohttp


async def main(loop):
    query = "Never gonna give you up"
    session = aiohttp.ClientSession()
    client = YoutubeClient(session)
    response = await client.search(query, max_results=5)
    await session.close()
    print(response)


loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
```

It works & does not show any error. Output:
```python
[{'id': 'DTLGSTwlqw0', 'thumbnails': ['https://i.ytimg.com/vi/DTLGSTwlqw0/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC1HppMxaTySwxDwO7LYNNeWI3K6A'], 'title': 'Marcus & Martinus - Never ft. OMI (Lyrics Terjemahan Indonesia) I will never ever let you go', 'long_desc': None, 'channel': 'Lirikyu', 'duration': '3:05', 'views': '260,324 views', 'publish_time': '6 months ago'}, {'id': '47CObT01wk0', 'thumbnails': ['https://i.ytimg.com/vi/47CObT01wk0/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAKX2KzTZ0cJQoLGA0P6PLJAlZvJg'], 'title': 'Rick Astley  Never Gonna Give You Up', 'long_desc': None, 'channel': 'Rick Astley', 'duration': '0:56', 'views': '25 views', 'publish_time': '6 months ago'}, {'id': 'ouEezpuPc3A', 'thumbnails': ['https://i.ytimg.com/vi/ouEezpuPc3A/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBOiulVBUjJXPcorMDsvSw2ifXK7Q', 'https://i.ytimg.com/vi/ouEezpuPc3A/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAIdP1RK6-9lbRdUJYpbF44gGHe8g'], 'title': 'Andy Grammer - "Don\'t Give Up On Me" [Official Video from the Five Feet Apart Film]', 'long_desc': None, 'channel': 'Andy Grammer', 'duration': '3:36', 'views': '75,525,802 views', 'publish_time': '2 years ago'}, {'id': 'r5fsxuVSUjM', 'thumbnails': ['https://i.ytimg.com/vi/r5fsxuVSUjM/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAKULj2BSXXgwe-LMggxVPcLx53eg', 'https://i.ytimg.com/vi/r5fsxuVSUjM/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD3O39N6hgOmiJ8nHMuQNWC7uOetw'], 'title': 'Andy Grammer - Don’t Give Up On Me lirik terjemahan ( soundtrack dari film Five Feet Apart)', 'long_desc': None, 'channel': 'Indolirik', 'duration': '3:15', 'views': '682,408 views', 'publish_time': '1 year ago'}, {'id': 'NdYWuo9OFAw', 'thumbnails': ['https://i.ytimg.com/vi/NdYWuo9OFAw/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDz_CJno0lIVGUltrUY68z3pB2_LA', 'https://i.ytimg.com/vi/NdYWuo9OFAw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCZe3t25YCc8oWzb9ayS-QoD08_Gw'], 'title': 'Goo Goo Dolls - Iris [Official Music Video]', 'long_desc': None, 'channel': 'Goo Goo Dolls', 'duration': '3:36', 'views': '302,648,502 views', 'publish_time': '11 years ago'}]
```

A way I could think to fix this issue is maybe you can help me debug in your machine, 

I just issued a new release & added a new parameter `raw` to the `.search()` function to return raw page content.

```python
# Upgrade
pip install -U ytpy

# Pass raw=True parameter
response = await client.search(query, max_results=5, raw=True)
```

Please let me know what the output is,

Thanks!

**Comment by izxxr** [comment]
Weird, I can't reproduce the bug on my machine. I'm hosting my discord bot on a hosting service and the error is raised when I run the bot there.

**Comment by izxxr** [comment]
Hi, Thanks for the help @madeyoga This is working as intended now. :+1:

**Comment by madeyoga** [comment]
if appropriate, can you share what the error is and how do you fix it? I still do not know what causes this error to occur

**Comment by izxxr** [comment]
Oh, The error was same.
```
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/container/sly/cogs/utility.py", line 235, in youtube
    response = await client.search(query, max_results=5)
  File "/home/container/.local/lib/python3.8/site-packages/ytpy/youtube.py", line 124, in search
    start_index = (page_content.index(start_feature) + len(start_feature) + 3)
ValueError: substring not found
```
And search term was "Never gonna give you up", I had to upgrade the package and it works now.
